config/routes.rb
Rails.application.routes.draw do

  get 'weather_predictions/new'

  get 'weathers/new'

  root to: 'country#show'

  get 'stats' => 'wpc#stats'

  get 'about' => 'about#About'
  get 'contact' => 'about#Contact'
  get 'history' => 'weathers#history'
  get '/pocasie/:name' => 'cities#show'
  get ':name' => 'wpc#weather'
  get 'stats/:page/:name' => 'wpc#stats'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <small>
      Aktuálne počasie je prevzaté z internetovej stránky <a href="http://www.meteo.sk/aktualne-pocasie/europa/slovenska-republika">Meteo.sk</a>
    </small>
    <ul>
      <small>
      <li>The Weather Prediction Comparator by Jakub Kazimír &copy </li>
      </small>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"> <%= link_to image_tag("logo-wpc.png", width:60, height: 35, border: 0)+"  Weather Prediction Comparator", root_path, id: "logo" %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Predpoveď", root_path %></li>
        <li><%= link_to "Štatistiky", stats_path %></li>
        <li><%= link_to "O projekte",   about_path %></li>
        <!--<li><%= link_to "Kontakt", contact_path %></li>-->
      </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-79388730-1', 'auto');
    ga('require', 'linkid');
    ga('send', 'pageview');

  </script>

  <%= render 'layouts/shim' %>
</head>
<body>

<div class="header">
  <%= render 'layouts/header' %>
</div>

<div class="body container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>


<!-- <%= debug(params) if Rails.env.development? %> -->

</body>
</html>